services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - KEYWORDS_API_KEY=${KEYWORDS_API_KEY}
      - KEYWORDS_API_URL=${KEYWORDS_API_URL}
      - REDIS_URL=${REDIS_URL}
      - AGENT_EMBEDDER_API_KEY=${AGENT_EMBEDDER_API_KEY}
      - NEXT_PUBLIC_EMBEDDER_SERVER_URL=${NEXT_PUBLIC_EMBEDDER_SERVER_URL}
      - API_ACCESS_KEY=${API_ACCESS_KEY}
    command: >
      bash -c '
        echo "Running init script..."
        npm run init
        echo "Copying Prisma files..."
        mkdir -p .output/server/node_modules/@magickml/server-db/src/lib/prisma/client-core/
        find ./node_modules/@magickml/server-db/src/lib/prisma/client-core/ -type f \( -name "libquery_engine-*" -o -name "schema.prisma" \) -exec cp {} .output/server/node_modules/@magickml/server-db/src/lib/prisma/client-core/ \;
        echo "Prisma client-core directory contents:"
        ls -la .output/server/node_modules/@magickml/server-db/src/lib/prisma/client-core/
        echo "Starting application..."
        npm start
      '
    env_file:
      - .env
